package configs

import (
	"os"
	"path/filepath"
	"testing"
)

func TestBuildGeneratedNginxRouteID(t *testing.T) {
	got := BuildGeneratedNginxRouteID("store", "Osprey CL/ES")
	if got != "auto_store_osprey_cl_es" {
		t.Fatalf("BuildGeneratedNginxRouteID() = %q, want %q", got, "auto_store_osprey_cl_es")
	}
}

func TestReplaceGeneratedNginxRoutesPreservesManualRoutes(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "madock-routes-*")
	if err != nil {
		t.Fatalf("os.MkdirTemp() error = %v", err)
	}
	defer os.RemoveAll(tmpDir)

	execDir := filepath.Join(tmpDir, "exec")
	projectName := "testproject"
	projectDir := filepath.Join(execDir, "projects", projectName)
	if err := os.MkdirAll(projectDir, 0755); err != nil {
		t.Fatalf("os.MkdirAll() error = %v", err)
	}

	t.Setenv("MADOCK_EXEC_DIR", execDir)
	CleanCache()

	configPath := filepath.Join(projectDir, "config.xml")
	SaveInFile(configPath, map[string]string{
		"nginx/routes/manual_route/host_ref":            "base",
		"nginx/routes/manual_route/path_prefix":         "/manual",
		"nginx/routes/manual_route/mage_run_code":       "manualstore",
		"nginx/routes/manual_route/mage_run_type":       "store",
		"nginx/routes/auto_store_old/host_ref":          "base",
		"nginx/routes/auto_store_old/path_prefix":       "/old",
		"nginx/routes/auto_store_old/mage_run_code":     "oldstore",
		"nginx/routes/auto_store_old/mage_run_type":     "store",
		"nginx/routes/auto_store_old/strip_path_prefix": "true",
	}, "default")

	err = ReplaceGeneratedNginxRoutes(projectName, "default", []NginxRoute{{
		ID:              "auto_store_new",
		HostRef:         "base",
		PathPrefix:      "/cl/es",
		MageRunCode:     "ospreycles",
		MageRunType:     "store",
		StripPathPrefix: true,
	}})
	if err != nil {
		t.Fatalf("ReplaceGeneratedNginxRoutes() error = %v", err)
	}

	config := ParseXmlFile(configPath)
	if _, ok := config["scopes/default/nginx/routes/manual_route/path_prefix"]; !ok {
		t.Fatal("manual route was removed")
	}
	if _, ok := config["scopes/default/nginx/routes/auto_store_old/path_prefix"]; ok {
		t.Fatal("old autogenerated route was not removed")
	}
	if config["scopes/default/nginx/routes/auto_store_new/path_prefix"] != "/cl/es" {
		t.Fatalf("new autogenerated route path = %q, want %q", config["scopes/default/nginx/routes/auto_store_new/path_prefix"], "/cl/es")
	}
	if config["scopes/default/nginx/routes/auto_store_new/host_ref"] != "base" {
		t.Fatalf("new autogenerated route host_ref = %q, want %q", config["scopes/default/nginx/routes/auto_store_new/host_ref"], "base")
	}
}
